import './globals.css'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App Ssr',
  description: 'Generated by create next app with ssr',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {/* <h1>
          Hi test
        </h1> */}
        {children}
      </body>
    </html>
  )
}
